apiVersion: v1
kind: ConfigMap
metadata:
  name: xxscreeps-config
  namespace: xxscreeps
data:
  .screepsrc.yaml: |
    mods:
      - '@xxscreeps/redis'
      - xxscreeps/mods/classic
      - xxscreeps/mods/backend/cookie
      - xxscreeps/mods/backend/password
      - xxscreeps/mods/backend/steam
      - xxscreeps/mods/prometheus
      - xxscreeps-mod-client
    database:
      data: redis://redis:6379
      pubsub: redis://redis:6379
      saveInterval: 120
    shards:
      - name: shard0
        data: redis://redis:6379/1
        pubsub: redis://redis:6379/2
        scratch: redis://redis:6379/2
    backend:
      bind: "*:21025"
      socketThrottle: 100
      allowEmailRegistration: true
    game:
      tickSpeed: 500
    processor:
      concurrency: 8
    runner:
      concurrency: 6
      sandbox: isolated
      cpu:
        memoryLimit: 256
        tickLimit: 500
  extra-dependencies.json: |
    {
      "dependencies": {
        "xxscreeps-mod-client": "^0.2.13",
        "screeps-client": "^0.10.0"
      }
    }
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dir /data
    appendonly yes
    save 60 1000
